### ISSUE TITLE
Inkscape not running from openshot

### ISSUE THREAD

**Issue by hmvago** [jssotomdz/openshot-snap#1]
Inside openshot there is a configuration to open/edit svg files with external app. inkscape but inkscape is not opening.
When I want to run inkscape from the "Title" feature I reaceive only a message saying that I have to install inkscape, inkscape is not been run.
I'm attaching 2 screenshots.

I'm uing:

- Ubuntu 20.04.6 LTS, 64-bit, Gnome version: 3.36.8
- openshot-community  3.1.1    jssotomdz  (snap)
- inkscape: inkscape  1.2.2-732a01da63-2022-12-09-cust  inkscape✓ (snap)

Thank you very much.
Hernan
![2023-07-16_10-21](https://github.com/jssotomdz/openshot-snap/assets/38031980/0f38f618-1d13-4c19-ad21-d40f71b0ff4f)
![2023-07-16_10-22](https://github.com/jssotomdz/openshot-snap/assets/38031980/e7c94f8b-4efa-4531-8e48-cbe83c159847)

**Comment by jssotomdz** [comment]
Hi!
Sorry for late reply, I understand the issue. The problem is that snaps aren't allowed to execute binaries that are outside of its container. For that to happen, openshot would need to be a classic snap and I don't think the store would approve for just a shortcut. So for now, please launch the apps as usual and import the assets. Sorry for the inconvenience.
Thanks!
